title: Samuel Durante 
email: samueldurante.h@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://samueldurantes.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samueldurantes
github_username:  samueldurantes

# Build settings
theme: minima
plugins:
  - jekyll-feed
